apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-dev
  namespace: argocd
spec:
  destination:
    namespace: httpbin-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: TODO
    repoURL: https://github.com/belghithahmed/argo.git
    targetRevision: HEAD
