apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-prod
  namespace: argocd
spec:
  destination:
    namespace: httpbin-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 004-kustomize/overlays/prod
    repoURL: https://github.com/belghithahmed/argo.git
    targetRevision: HEAD
    kustomize:
      commonAnnotations:
        merry: christmas-fulks
      namePrefix: prod-
